# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/classify-image
Accept: application/json

###

GET http://127.0.0.1:8000/classify-sentiment
Accept: application/json

###

GET http://127.0.0.1:8000/predict-masked-word
Accept: application/json

###

GET http://127.0.0.1:8000/train-test-ner
Accept: application/json

###
